################################################
#                                              #
# This is my main configuration.yaml. I use    #
# a package-based split-configuration format,  #
# please see the ReadMe files for details on   #
# how this is done, and thusly how this repo   #
# is organised in to the various files/folders #
#                                              #
################################################


homeassistant:
  name: Home Assistant

  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation

  time_zone: !secret time_zone
  unit_system: metric

  packages:
    # Common
    common_service: !include packages/common/service.yaml
    common_http: !include packages/common/http.yaml
    common_zones: !include packages/common/zones.yaml
    # Security
    security: !include packages/security/root.yaml
    # Trash
    trash: !include packages/trash/root.yaml
    # Rooms
    bathroom: !include packages/rooms/bathroom/root.yaml
    # System
    system: !include packages/system/root.yaml


group: !include groups.yaml