#---------
# GROUPS
#---------

#---------
# Customize
#---------
homeassistant:
  customize:
    plant.anthurium_andraeanum:
      friendly_name: Anthurium andraeanum (Living room)
      entity_picture: /local/flowers/anthurium_andreanum.jpg
    plant.stephanotis_floribunda:
      friendly_name: Stephanotis floribunda (Living room)
      entity_picture: /local/flowers/stephanotis_floribunda.jpg

#---------
# Plant
#---------
plant:
  anthurium_andraeanum:
      sensors:
        moisture: sensor.anthurium_andraeanum_moisture
        battery: sensor.anthurium_andraeanum_battery
        temperature: sensor.anthurium_andraeanum_temperature
        conductivity: sensor.anthurium_andraeanum_conductivity
        brightness: sensor.anthurium_andraeanum_brightness
      min_moisture: 23
      max_moisture: 65
      min_battery: 15
      min_conductivity: 500
      max_conductivity: 2000
      min_temperature: 15
      max_temperature: 32
      min_brightness: 1500
      max_brightness: 35000

  stephanotis_floribunda:
      sensors:
        moisture: sensor.stephanotis_floribunda_moisture
        battery: sensor.stephanotis_floribunda_battery
        temperature: sensor.stephanotis_floribunda_temperature
        conductivity: sensor.stephanotis_floribunda_conductivity
        brightness: sensor.stephanotis_floribunda_brightness
      min_moisture: 23
      max_moisture: 65
      min_battery: 15
      min_conductivity: 500
      max_conductivity: 2000
      min_temperature: 15
      max_temperature: 32
      min_brightness: 1500
      max_brightness: 35000

#---------
# Sensor
#---------
sensor:
  - platform: miflora
    mac: !secret flower_miflora_anthurium_mac
    name: Anthurium andraeanum
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
  
  - platform: miflora
    mac: !secret flower_miflora_stephanotis_mac
    name: Stephanotis floribunda
    force_update: false
    median: 3
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery