# ------------------
# HOME
# ------------------
default_view:
  view: yes
  name: Home
  icon: mdi:home

# ------------------
# SECURITY
# ------------------
security:
  view: yes
  name: Security
  icon: mdi:security

# ------------------
# Living room
# ------------------
livingroom:
  view: yes
  name: Living room
  icon: mdi:sofa

# ------------------
# Desk office
# ------------------
deskoffice:
  view: yes
  name: Desk office
  icon: mdi:desk-lamp

# ------------------
# Bed rooms
# ------------------
bedrooms:
  view: yes
  name: Bed rooms
  icon: mdi:hotel

# ------------------
# Flowers
# ------------------
flower:
  view: yes
  name: Flowers
  icon: mdi:flower

# ------------------
# System
# ------------------
system:
  view: yes
  name: System
  icon: mdi:cellphone-arrow-down
  entities:
    - group.raspberry
    - group.speedtest