homeassistant:
  customize: !include customize.yaml

group: !include group.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensor.yaml
automation: !include automation.yaml