- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: mqtt
  state_topic: "/home/trashpickupday"
  name: "Trash Pickup Day"
  value_template: "{{ value }}"
  qos: 1
- platform: mqtt
  state_topic: "/home/recyclepickupday"
  name: "Recycle Pickup Day"
  value_template: "{{ value }}"
  qos: 1
- platform: mqtt
  state_topic: "/home/recyclepickupweek"
  name: "Recycle Pickup Week"
  value_template: "{{ value }}"
  qos: 1
###############################################################################
# Sensor to hold info about current week is an odd week or an even week of the year
###############################################################################
- platform: template
  sensors:
    current_week:
      value_template: >-
        {% set year = states.sensor.date__time.state.split(',')[0].split('-')[0] %}
        {% set month = states.sensor.date__time.state.split(',')[0].split('-')[1] %}
        {% set date = states.sensor.date__time.state.split(',')[0].split('-')[2] %}
        {% set today = strptime(year ~ '-' ~ month ~ '-' ~ date , '%Y-%m-%d') %}
        {%- if (as_timestamp(today) | timestamp_custom('%U', true) | int ) % 2 == 0 -%}
          Even Week (Week# {{ as_timestamp(today) | timestamp_custom('%U', true) }})
        {%- else -%}
          Odd Week (Week# {{ as_timestamp(today) | timestamp_custom('%U', true) }})
        {%- endif -%}
###############################################################################
# Trash  - Pickup schedule is EVERY week.
# Set the day to a day before the actual day leaving time for reminders
###############################################################################
- platform: template
  sensors:
    trash_day:
      value_template: >-
        {% set year = states.sensor.date__time.state.split(',')[0].split('-')[0] %}
        {% set month = states.sensor.date__time.state.split(',')[0].split('-')[1] %}
        {% set date = states.sensor.date__time.state.split(',')[0].split('-')[2] %}
        {% set today = strptime(year ~ '-' ~ month ~ '-' ~ date , '%Y-%m-%d') %}
        {%- set pickupDay = states.sensor.trash_pickup_day.state | lower -%}
        {%- if as_timestamp(today)| timestamp_custom('%A', true) | lower == pickupDay -%}
          yes
        {%- else -%}
          no
        {%- endif -%}
###############################################################################
# Recycle - Pickup schedule is every other week.
# Set the day to a day before the actual day leaving time for reminders
###############################################################################
- platform: template
  sensors:
    recycle_day:
      value_template: >-
        {% set year = states.sensor.date__time.state.split(',')[0].split('-')[0] %}
        {% set month = states.sensor.date__time.state.split(',')[0].split('-')[1] %}
        {% set date = states.sensor.date__time.state.split(',')[0].split('-')[2] %}
        {% set today = strptime(year ~ '-' ~ month ~ '-' ~ date , '%Y-%m-%d') %}
        {%- set pickupDay = states.sensor.recycle_pickup_day.state | lower -%}
        {% if states.input_select.recycle_pickup_week.state | lower == "even weeks" %}
          {%- set evenWeekPickup = "true" %}
        {% else %}
          {%- set evenWeekPickup = "false" %}
        {% endif %}
        {%- macro day_of_week(timestamp) -%}
          {{ as_timestamp(timestamp)| timestamp_custom('%A', true) | lower }}
        {%- endmacro %}
        {%- macro week_number_of_year() -%}
          {{ as_timestamp(today) | timestamp_custom('%U', true) | int }}
        {%- endmacro %}
        {%- macro is_it_this_week() -%}
          {%- if as_timestamp(today) | timestamp_custom('%U', true) | int % 2 == 0 -%}
            {%- if evenWeekPickup == "true" -%}
              true
            {%- else -%}
              false
            {%- endif -%}
          {%- else -%}
            {%- if evenWeekPickup == "true" -%}
              false
            {%- else -%}
              true
            {%- endif -%}
          {%- endif -%}
        {%- endmacro -%}
        {%- macro is_it_today() -%}
        {%- if is_it_this_week() == "true" -%}
          {%- if day_of_week(today) | lower == pickupDay -%}
            yes
          {%- else -%}
            no
          {%- endif -%}
        {%- else -%}
          no
        {%- endif -%}
        {%- endmacro -%}
        {{- is_it_today() -}}