#--------------
# GROUP
#--------------
group:
  bedrooms_temperature:
    name: Bedrooms Temperature
    view: no
    entities:
      - sensor.master_bedroom_sensor
      - sensor.second_child_bedroom_sensor

#--------------
# SENSORS
#--------------
sensor:
  - platform: zigate
    name: 'Master bedroom Sensor'
    address: !secret zigate_sensor_master_bedroom_address
    default_state: temperature
    default_unit: '°C'
  - platform: zigate
    name: 'First Child bedroom Sensor'
    address: !secret zigate_sensor_first_child_bedroom_address
    default_state: temperature
    default_unit: '°C'
  - platform: zigate
    name: 'Second Child bedroom Sensor'
    address: !secret zigate_sensor_second_child_bedroom_address
    default_state: temperature
    default_unit: '°C'