################################################
#                                              #
# This package creates a device that allows me #
# to set a boolean to show the system in       #
# "Maintenance Mode", and manage backing up,   #
# upgrading and pulling config from Github     #
#                                              #
################################################

homeassistant:  
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml

alert: !include alert.yaml
automation: !include automation.yaml
script: !include script.yaml
shell_command: !include shell_command.yaml
switch: !include switch.yaml
weblink: !include weblink.yaml
